/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnotationBar: typeof import('./../components/AnnotationBar/index.vue')['default']
    Annotations: typeof import('./../components/Annotations/index.vue')['default']
    AnnotationSelect: typeof import('./../components/AnnotationBar/AnnotationSelect.vue')['default']
    AnnotationSelect2: typeof import('./../components/AnnotationBar/AnnotationSelect2.vue')['default']
    BookmarkNode: typeof import('./../components/Bookmarks/BookmarkNode.vue')['default']
    Bookmarks: typeof import('./../components/Bookmarks/index.vue')['default']
    CollapseTransition: typeof import('./../components/CollapseTransition/index.vue')['default']
    ColorBlock: typeof import('./../components/ColorPicker/ColorBlock.vue')['default']
    ColorPicker: typeof import('./../components/ColorPicker/index.vue')['default']
    ColorPickerPannel: typeof import('./../components/ColorPicker/ColorPickerPannel.vue')['default']
    GradientBar: typeof import('./../components/ColorPicker/GradientBar.vue')['default']
    InputHex: typeof import('./../components/ColorPicker/InputHex.vue')['default']
    InputNumber: typeof import('./../components/ColorPicker/InputNumber.vue')['default']
    MyFavorite: typeof import('./../components/ColorPicker/MyFavorite.vue')['default']
    MyFavrite: typeof import('./../components/ColorPicker/MyFavrite.vue')['default']
    NavBar: typeof import('./../components/NavBar/index.vue')['default']
    NModal: typeof import('naive-ui')['NModal']
    OpacityBar: typeof import('./../components/ColorPicker/OpacityBar.vue')['default']
    PageNumber: typeof import('./../components/PageNumber/index.vue')['default']
    PdfRenderer: typeof import('./../components/PdfRenderer/index.vue')['default']
    Picker: typeof import('./../components/ColorPicker/Picker.vue')['default']
    PickerBlock: typeof import('./../components/ColorPicker/PickerBlock.vue')['default']
    PickerHue: typeof import('./../components/ColorPicker/PickerHue.vue')['default']
    PickerInputs: typeof import('./../components/ColorPicker/PickerInputs.vue')['default']
    PickerMenu: typeof import('./../components/ColorPicker/PickerMenu.vue')['default']
    PickerPannel: typeof import('./../components/ColorPicker/PickerPannel.vue')['default']
    PickerPresets: typeof import('./../components/ColorPicker/PickerPresets.vue')['default']
    SkButton: typeof import('./../components/SkButton/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Thumbnails: typeof import('./../components/Thumbnails/index.vue')['default']
    ToolBar: typeof import('./../components/ToolBar/index.vue')['default']
  }
}
