/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {};

declare module "vue" {
  export interface GlobalComponents {
    ToolBar: (typeof import("./../components/ToolBar/index.vue"))["default"];
    NavBar: (typeof import("./../components/NavBar/index.vue"))["default"];
    AnnotationBar: (typeof import("./../components/AnnotationBar/index.vue"))["default"];
  }
}
